### ISSUE TITLE
"Disconnect to Connect" error

### ISSUE THREAD

**Issue by timbuktu234** [pvg/nvtemp#1]
This recompiled version works on High Sierra, but sadly gives the error "Changed notes could not be saved because a parameter was invalid" every few seconds.
<img width="532" alt="screen shot 2017-08-24 at 10 47 14 am" src="https://user-images.githubusercontent.com/460897/29680507-9a6abdc6-88b9-11e7-8f7c-46608aee3993.png">

**Comment by pvg** [comment]
There's a missing header in nvALT for Simplenote integration which presumably contains an API key/credentials and is not included. There's a sample header with dummy credentials which is what I used to build this so it won't work with Simplenote. This build is really just a stopgap so at an absolute minimum you can get your data out - something that's surprisingly tricky without a working nv app.

**Comment by timbuktu234** [comment]
I am syncing through Dropbox (the Simplenote sync option is off and I do not use it), but still gives this error message. Is that normal?
